on:
  push:
    branches:
      - main

name: create GitHub release

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: dgellow/release-please-action@main
        with:
          release-type: node
          default-branch: main
          command: github-release
