on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: create GitHub release

jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: dgellow/release-please-action@main
        with:
          release-type: node
          default-branch: main
          command: github-release
