on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: dgellow/release-please-action@main
        with:
          release-type: node
          package-name: my-cool-package
          default-branch: main
          changes-branch: next
